### ISSUE TITLE
Plugin submission

### ISSUE THREAD

**Issue by orthagh** [ticgal/borgbase#1]
Hello

I received your plugin submission on plugins.glpi-project.org.

Please, fix in your xml the following issues:

- a logo is mandary
- could you provide some screenshots to illustrate
- compatibility node should be in a semver notation, ex `~10.0.3`, check [semver-check tool to be sure](https://jubianchi.github.io/semver-check/#/)
- you provide a download_url, do you want a marketplace inclusion ?

Regards

**Comment by OscarBeiro** [comment]
Hi @orthagh ,

I think I mess with the link. We usually create a different branch to that kind of info (multimedia).
This is the right XML: https://raw.githubusercontent.com/ticgal/borgbase/multimedia/borgbase.xml

We will remove the wrong XML ASAP.
Regards,

**Comment by OscarBeiro** [comment]
And of course we'd love to see it at the marketplace.
Regards,

**Comment by orthagh** [comment]
Done, the plugin should appears in the plugins directory and marketplace within the day (with cache expiration)
